branch-defaults:
  master:
    environment: summercamp
global:
  application_name: SummerCamp
  default_ec2_keyname: andrew
  default_platform: 64bit Amazon Linux 2015.09 v2.0.8 running Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
